define vivian = Character("Vivian")
define chara = Character('Саша', color = "#2594da")
define mom = Character('Мама', color="#9c35e6")
define skelet = Character('Водитель', color="#eacc09")
define farmer = Character('Маша',color="#31ac04")
define dev = Character("Никита",color = "#1000bd")
define kinght = Character("Вова",color = "#be2001")
define laziness = Character("Лень", color = "#ac64ea")
define bad_thoughts = Character("Плохие мысли", color = "#3d6605")
define fear = Character ("Страх", color = "#d90e30ff")